### PR TITLE
Fix: clients need to pay full price without discounts

### LINKED ISSUE #109: Discounts ignored - customers charged full price
- Simplepay Gateway bővítmény verzió: 2.5.4
- WooCommerce verzió: 7.0.0
- WordPress verzió: 6.0.3
- PHP verzió: 8.1.11

### Leírás
On line 122 you discard the negative amounts from the order, so clients with a discount (redeeming loyalty points for example) are charged for the full price. There is a discount field (line 41) that seems ignored as well.
https://github.com/conedevelopment/simplepay-gateway/blob/master/src/Payloads/PaymentPayload.php#L122
Thanks for your help as we have the issue on 2 production sites now.

### Reprodukáláshoz szükséges lépések
Client orders items, redeems loyalty points, the checkout page and the cart page show the right amounts, but with this method of payment they get charged the full amount thus ignoring the discount.

### PR DESCRIPTION
**Pull request by Tofandel**
When paying for an order, discounts are ignored and the customer is asked to pay for the full price.. This is a huge issue as then customers need to get refunded

Fixes #109

### CODE REVIEW

**Comment by iamgergo** [comment]
Hi,

Thanks for the PR (and sorry for the late answer). The answer why we pass 0 discount: https://github.com/conedevelopment/simplepay-gateway/issues/109#issuecomment-1362585630

**Comment by Tofandel** [comment]
That's funny because I tested that and it worked fine, without this fix the price to pay is incorrect

The discount calculation doesn't work for negative fees

**Comment by iamgergo** [comment]
So, are you sure negative discount values won't break anything here?

**Comment by Tofandel** [comment]
I tried both negative and positive in discount it does exactly the same, the simple pay api already takes the `abs` value, the doc does say discount should be positive so I abs it

image

And yes I'm sure it won't break anything

**Comment by iamgergo** [comment]
So I think, I misunderstood the complete thing here from the beginning. I don't know why, but I thought you are calculating the original discounts (not negative fees but for example coupons). 

The limitation I was refering to was about that, and not the negative fees. So actually your code here makes sense.

My two questions:
- are you sure `line_item`s should be parsed here as well? Normal products should not have negative prices.
- why are you casting the shipping total to float explicitly?

**Comment by Tofandel** [comment]
> are you sure line_items should be parsed here as well? Normal products should not have negative prices.

They should not but its in theory possible and this is just meant to complement the previous calculation so that all prices are taken into account no matter what, positives in 'items' and negatives all added up as discount

> why are you casting the shipping total to float explicitly

Woocommerce is sending this values as string and not as a float so addition here is confusing (especially if you've been traumatised by js addition before 😂) and ide was complaining quite strongly about it, php is already casting it to float after some magic because of the addition, but better to be explicit

File: src/Payloads/PaymentPayload.php [hunk 1]
```diff
@@ -103,6 +103,23 @@ protected static function delivery(WC_Order $order)
...
+     * Get the total discount of the order.
+     *
+     * @param  \WC_Order  $order
+     * @return float
+     */
+    protected static function discount(WC_Order $order)
+    {
+        return array_reduce($order->get_items(['line_item', 'fee']), function ($total, $item) {
+            if ($item->get_total() < 0) {
+                $total += abs($item->get_total() + $item->get_total_tax());
```
Comment (iamgergo) [inline src/Payloads/PaymentPayload.php:116]: @Tofandel I changed the item mapping here, because theoritically it is possible to have bigger quantities of one fee, line item than one. Even if it's not very common. Can you confirm, that this works for you, please?

Comment (Tofandel) [reply src/Payloads/PaymentPayload.php:116]: I tested it, and yes it works fine 👍

Comment (iamgergo) [reply src/Payloads/PaymentPayload.php:116]: Great, thanks! Yep, soon I'll release it.
